// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv98b7bkCIz_H_ihlGe9oMngO4g4u8Qps',
    appId: '1:935263867239:web:ec3bab8f6963fc04e95fc2',
    messagingSenderId: '935263867239',
    projectId: 'wasalny-fc5c3',
    authDomain: 'wasalny-fc5c3.firebaseapp.com',
    storageBucket: 'wasalny-fc5c3.firebasestorage.app',
    measurementId: 'G-0WLX42B03S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD24NyQX8Nnkr4yUVnCUQQF55FhGgn7mAw',
    appId: '1:935263867239:android:15f7130ec994c53ce95fc2',
    messagingSenderId: '935263867239',
    projectId: 'wasalny-fc5c3',
    storageBucket: 'wasalny-fc5c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqtEH2hB7appSYWdIQ_UEqP8DnLjcpAJE',
    appId: '1:935263867239:ios:7444b0d88bb13813e95fc2',
    messagingSenderId: '935263867239',
    projectId: 'wasalny-fc5c3',
    storageBucket: 'wasalny-fc5c3.firebasestorage.app',
    iosBundleId: 'com.example.waslny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqtEH2hB7appSYWdIQ_UEqP8DnLjcpAJE',
    appId: '1:935263867239:ios:7444b0d88bb13813e95fc2',
    messagingSenderId: '935263867239',
    projectId: 'wasalny-fc5c3',
    storageBucket: 'wasalny-fc5c3.firebasestorage.app',
    iosBundleId: 'com.example.waslny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv98b7bkCIz_H_ihlGe9oMngO4g4u8Qps',
    appId: '1:935263867239:web:8c75691178bf18e3e95fc2',
    messagingSenderId: '935263867239',
    projectId: 'wasalny-fc5c3',
    authDomain: 'wasalny-fc5c3.firebaseapp.com',
    storageBucket: 'wasalny-fc5c3.firebasestorage.app',
    measurementId: 'G-3Z27XK7Y4V',
  );
}
